# numpy 概要と注意点

## 要素が 0, 1, 2, ..., 100000 のリスト(配列)を作る

In [6]:
# 1. なじみのある書き方
l1 = [] # リストを初期化
for i in range(0, 100000):
    l1.append(i)

# 2. python な書き方．リスト内包表現と言います
l2 = [i for i in range(0, 100000)]

# 3. 実は range だけでいい．range が返すものが実はリスト
l3 = range(0, 100000)

## sinθ を計算
sin0, sin1, ..., sin100000 すなわち，10万回 sin を計算します．

### math 版

In [2]:
import math
import numpy as np
import time

n = 100000

# math 版
start = time.time()
l = [math.sin(i) for i in np.arange(0, n)]
print(time.time() - start)

0.024013042449951172


### numpy 版
sinの引数に(多次元)配列をとることができるのが特徴

他の関数も似たような作り

In [3]:
start = time.time()
l = np.sin(np.arange(0, n))
print(time.time() - start)

0.0025043487548828125


numpyのほうが10倍くらい速い

## 行列を作る

In [19]:
# 3x3 の行列を作る
a = np.array([[5, 0, 1],
              [4, 5, 6],
              [7, 2, 9]])
a

array([[5, 0, 1],
       [4, 5, 6],
       [7, 2, 9]])

## 行列の積

In [20]:
# 行列の積
# b = a * a だと要素ごとの積
b = np.dot(a, a)
b

array([[ 32,   2,  14],
       [ 82,  37,  88],
       [106,  28, 100]])

## 逆行列
行列式が 0 にならないことを確認

In [21]:
np.linalg.det(a)

137.99999999999994

逆行列を求める

In [22]:
# 逆行列
c = np.linalg.inv(a)
c

array([[ 0.23913043,  0.01449275, -0.03623188],
       [ 0.04347826,  0.27536232, -0.1884058 ],
       [-0.19565217, -0.07246377,  0.18115942]])

## 元の行列 * 逆行列 = 単位行列になるはず

In [23]:
# 単位行列になるはず
np.dot(a, c)

array([[  1.00000000e+00,  -6.93889390e-17,   5.55111512e-17],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [ -2.22044605e-16,   0.00000000e+00,   1.00000000e+00]])

ちょっとゴミが出ますがほぼ単位行列です

## 行列式が0の場合

In [26]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

行列式 0 でも逆行列求める時にエラーにならないです．変な値になってるので気付くけど

In [28]:
c = np.linalg.inv(a)
c

array([[ -4.50359963e+15,   9.00719925e+15,  -4.50359963e+15],
       [  9.00719925e+15,  -1.80143985e+16,   9.00719925e+15],
       [ -4.50359963e+15,   9.00719925e+15,  -4.50359963e+15]])

元の行列と逆行列の積もおかしい

In [29]:
np.dot(a, c)

array([[ 0.,  0.,  0.],
       [-4.,  0., -4.],
       [ 0.,  0.,  0.]])